#!/bin/sh

horaActual1=$(date +%H%M) #Define hora actual
horacomienzo=2018 #Hora a la que empieza a tomar fotos
horalim1=2050 #Hora a la que anochece
while [ $horaActual1 -le $horacomienzo ]
do
    echo "Muy temprano todavia! Espero 30s"
    echo "Son las: $horaActual1 | Arranca a las: $horacomienzo"
    sleep 30s
    horaActual1=$(date +%H%M)
done

while [ $horaActual1 -le $horalim1 ]
do
    setfilter v
    sleep 10s
    tomaexpo skyv 1 1 1 2 2 0
    tomaexpo skyv 1 2 1 2 2 0
    tomaexpo skyv 1 4 1 2 2 0
    tomaexpo skyv 1 6 1 2 2 0
    setFilter r
    sleep 10s
    tomaexpo skyr 1 1 1 2 2 0
    tomaexpo skyr 1 2 1 2 2 0
    tomaexpo skyr 1 4 1 2 2 0
    tomaexpo skyr 1 6 1 2 2 0
    setFilter i
    sleep 10s
    tomaexpo skyi 1 1 1 2 2 0
    tomaexpo skyi 1 2 1 2 2 0
    tomaexpo skyi 1 4 1 2 2 0
    tomaexpo skyi 1 6 1 2 2 0

    horaActual1=$(date +%H%M)

done

tomaexpo bias 20 0 0.0025 2 2 0
