#!/bin/sh

teleSleep #Duerme al telescopio para que no trackee
horaActual1=$(date +%H%M) #Define hora actual
horacomienzo=2010 #Hora a la que empieza a tomar fotos
horalim1=2050 #Hora a la que anochece
while [ $horaActual1 -le $horacomienzo]
do
    echo 'Muy temprano todavia: espero 30s'
    sleep 30s
    horaActual1=$(date +%H%M)
done

while [ $horaActual1 -le $horalim1 ]
do
    setFilter clear
    sleep 10s
    tomaexpo skyc 1 1 1 2 2 0
    tomaexpo skyc 1 2 1 2 2 0
    tomaexpo skyc 1 4 1 2 2 0
    tomaexpo skyc 1 6 1 2 2 0
    setFilter u
    sleep 10s
    tomaexpo skyu 1 1 1 2 2 0
    tomaexpo skyu 1 2 1 2 2 0
    tomaexpo skyu 1 4 1 2 2 0
    tomaexpo skyu 1 6 1 2 2 0
    setFilter b
    sleep 10s
    tomaexpo skyb 1 1 1 2 2 0
    tomaexpo skyb 1 2 1 2 2 0
    tomaexpo skyb 1 4 1 2 2 0
    tomaexpo skyb 1 6 1 2 2 0

    horaActual1=$(date +%H%M)

done

tomaexpo bias 20 0 0.0025 2 2 0
