#!/bin/sh

filtro="i"
bin=2
m=0
setFilter $filtro
sleep 10s

horaActual1=$(date +%H%M) #Define hora actual
horacomienzo=2010 #Hora a la que empieza a tomar fotos
while [ $horaActual1 -le $horacomienzo ]
do
    echo "Muy temprano todavia! Espero 30s"
    echo "Son las: $horaActual1 | Arranca a las: $horacomienzo"
    sleep 30s
    horaActual1=$(date +%H%M)
done

openDome
sleep 120s

while [ $m -eq 0 ] ; do
	n=0
	while [ $n -eq 0 ] ; do
		a=`ssh mate Leerluz_iafe1.py $filtro $bin`

		if [ ${a%%.*} -eq 0 ] ; then
            #Leerluz devuelve a = 0 si estoy fuera del rango de luz para tomar
            #flats (mucha luz) esta cosa con "a" chequea la parte entera
			echo 'Hay mucha luz, esperar...'
			sleep 5s


		elif [ ${a%%.*} -eq -1 ] ; then
            #Devuelve a=-1 si estoy fuera del rango para tomar flats (poca luz)
			echo 'Hay poca luz, tarde para flats'
			n=1
			m=1

		elif [ ${a%%.*} -ge 1 ] ; then
            #Si lo que devuelve leerluz es un numero
			tomaexpo sky$filtro 1 $a 1 $bin $bin 0
			n=1
		else
            #En caso contrario (si leerluz no devuelve un numero es que ando
            #anda mal, basicamente que no puede leer el archivo CloudWatcher.csv)
			echo 'Leerluz.py no esta funcionando, revisar el software de la estación '
			sleep 50s
			n=1
			m=1
		fi
	done
done

tomaexpo bias 20 0 0.0025 2 2 0

#python /home/telescopio/FLATS/AnalisisPython/MasterFlat.py
