#!/bin/sh

filtro=${1:-1}
bin=${2:-1}

setfilter  $filtro
sleep 5s
#horaActual=1300
n=0
while [ $n -eq 0 ] ; do
	horaActual=$(date +%H%M)
	a=`Leerluz $filtro $bin`
	if [ ${a%%.*} -eq 0 ] ; then	#Leerluz devuelve a = 0 si estoy fuera del rango de luz para tomar flats (mucha luz) esta cosa con "a" chequea la parte entera	
		if [ $horaActual -ge 1200 ] ; then		
			echo 'Hay mucha luz, esperar...'
			sleep 5s
		else
			echo 'Hay mucha luz, CERRAR TODO'
			killall session
			closeSession
			n=1
		fi
	
	
	elif [ ${a%%.*} -eq -1 ] ; then	#Devuelve a=-1 si estoy fuera del rango para tomar flats (poca luz)
		if [ $horaActual -ge 1200 ] ; then
			echo 'Hay poca luz, tarde para flats'
			n=1
		else		
			echo 'Hay poca luz, esperar...'
			sleep 5s
		fi
	elif [ ${a%%.*} -ge 1 ] ; then  #Si lo que devuelve leerluz es un numero 
		tomaexpo sky$filtro 1 $a 1 $bin $bin 0
		n=1
	else				#En caso contrario (si leerluz no devuelve un numero es que ando anda mal, basicamente que no puede leer el archivo CloudWatcher.csv)
		echo 'Leerluz.py no esta funcionando, revisar el software de la estación '
		sleep 50s
		n=1
		
	fi
done
